### ISSUE TITLE
absolute path 10k lần thứ nhất 

### ISSUE THREAD

**Issue by ndthien98** [duchieu307/nestjs-nghichngom#11]
https://github.com/duchieu307/nestjs-nghichngom/blob/672ec7417c53275d1d92f9d41c91afe5dcf5bee2/test/app.e2e-spec.ts#L4

**Comment by duchieu307** [comment]
![image](https://user-images.githubusercontent.com/33222886/132614647-bdb0a669-0320-434b-90cf-92cbfbfc89b3.png)
khoong phai chua fix ma la chua push

**Comment by ndthien98** [comment]
thế thì thêm 10k vì tội chưa push mà closed issue là 20k
