### ISSUE TITLE
hạn chế destruct

### ISSUE THREAD

**Issue by ndthien98** [duchieu307/nestjs-nghichngom#5]
https://github.com/duchieu307/nestjs-nghichngom/blob/672ec7417c53275d1d92f9d41c91afe5dcf5bee2/src/modules/tasks/task.repository.ts#L13

hạn chế destrucct các thuộc tính ra vì cách hoạt động của destruct là tạo 1 biến mới rồi copy value sang

**Comment by duchieu307** [comment]
oke
